version: '3'

services:
  web:
    image: temporalio/web:latest
    build: .
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - 8088:8088
